input {
  beats {
    port => 5044
  }
}

filter {

  # =====================================================
  # KEEP ONLY APPLICATION CONTAINER LOGS
  # =====================================================

  if [container][name] != "blog-app" {
    drop {}
  }

  # =====================================================
  # NORMALIZE FIELDS
  # =====================================================

  mutate {
    rename => {
      "logger_name" => "logger"
    }

    remove_field => [
      "agent",
      "ecs",
      "input",
      "host",
      "log",
      "container",
      "stream"
    ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "blog-logs-%{+YYYY.MM.dd}"
    retry_on_conflict => 3
  }

  # Debug only
  stdout {
    codec => rubydebug
  }
}