version: "3.9"

networks:
  blog-net:
    driver: bridge

volumes:
  es-data:
  app-logs:
  filebeat-data:
  pg-data:
  redis-data:

services:
  postgres:
    image: postgres:16-alpine
    container_name: blog-management-postgres

    environment:
      POSTGRES_DB: ${RDS_DB_NAME}
      POSTGRES_USER: ${RDS_USERNAME}
      POSTGRES_PASSWORD: ${RDS_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - pg-data:/var/lib/postgresql/data

    networks:
      - blog-net

    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${RDS_USERNAME} -d ${RDS_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: blog-management-redis

    command: redis-server --requirepass "${REDIS_PASSWORD}"

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - blog-net

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch

    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false

    ports:
      - "9200:9200"

    volumes:
      - es-data:/usr/share/elasticsearch/data

    networks:
      - blog-net

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -u elastic:${ELASTIC_PASSWORD} http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\\|yellow\"'"
        ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"


  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana

    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}

    ports:
      - "5601:5601"

    networks:
      - blog-net

    restart: unless-stopped

    depends_on:
      elasticsearch:
        condition: service_healthy

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash

    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - LS_JAVA_OPTS=-Xms256m -Xmx256m

    volumes:
      - ./elk-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro

    ports:
      - "5044:5044"
      - "9600:9600"

    networks:
      - blog-net

    restart: unless-stopped

    depends_on:
      elasticsearch:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"


  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.0
    container_name: filebeat

    user: root

    command: ["filebeat", "-e", "--strict.perms=false"]

    volumes:
      - ./elk-config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - app-logs:/usr/share/filebeat/app-logs:ro
      - filebeat-data:/usr/share/filebeat/data

    networks:
      - blog-net

    restart: unless-stopped

    depends_on:
      logstash:
        condition: service_healthy

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  blog-app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: blog-app

    environment:
      - RDS_USERNAME=${RDS_USERNAME}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - RDS_HOSTNAME=postgres
      - RDS_PORT=5432
      - RDS_DB_NAME=${RDS_DB_NAME}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    ports:
      - "8080:8080"

    volumes:
      - app-logs:/app/logs

    networks:
      - blog-net

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      logstash:
        condition: service_healthy

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    develop:
      watch:
        - action: rebuild
          path: ./src
