filebeat.inputs:
  - type: container
    enabled: true

    paths:
      - /var/lib/docker/containers/*/*.log

    processors:
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

      - add_docker_metadata: ~

      - drop_event:
          when:
            regexp:
              requestUri: "^/actuator/health$"

output.logstash:
  hosts: [ "logstash:5044" ]

queue.mem:
  events: 8192
  flush.min_events: 512
  flush.timeout: 1s

logging.level: info
logging.to_files: false

setup.ilm.enabled: false

filebeat.registry.path: /usr/share/filebeat/data/registry
