spring.application.name=Blog Management System
logging.level.org.springframework=INFO
spring.mvc.log-resolved-exception=true

# DB Configuration
spring.datasource.url=jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
#Check N+1 query
spring.jpa.properties.hibernate.generate_statistics=true
#Enable SQL initialization for non-embedded databases
spring.sql.init.mode=always

# Enable Actuator Endpoints
management.endpoints.web.exposure.include=*
#increase the number of processes available for scheduling
spring.task.scheduling.pool.size=5

# Server Configuration
server.servlet.context-path=/api/v1
server.port=8080

# Swagger Configuration
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json

# Security Configuration
jwt.secretKey=${JWT_SECRET_KEY}

# Frontend URL
app.base.url=${FRONTEND_URL}

# Scheduling Configuration
blog.schedulers.userDeletion.cron=0 0 0 * * *
blog.schedulers.viewSync.cron=0 */5 * * * *
blog.schedulers.publishPost.cron=0 * * * * *

# Data Compression
server.compression.enabled=true

# Mail Configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# Freemarker Configuration
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftlh
spring.freemarker.content-type=text/plain

# Sender address
app.mail.from=${MAIL_FROM}

# Redis Configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

#docker run \
#--name blog-management-postgres \
#-e POSTGRES_PASSWORD=blog_admin \
#-e POSTGRES_USER=root \
#-e POSTGRES_DB=blog_management_system \
#-p 5433:5432 \
#postgres:16.13-alpine3.23@sha256:6ba5f528786dcc296ab4b6d70c1699d224659583e6df320ee1c39e33b4111820
#docker run -d \
#  --name blog-management-redis \
#  -p 6379:6379 \
#  redis:7-alpine \
#  redis-server --requirepass "blog_redis"