spring.application.name=Blog_Management_System
logging.level.org.springframework=INFO

# DB Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/blog_management_system}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:blog_admin}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
#Check N+1 query
spring.jpa.properties.hibernate.generate_statistics=true
#Enable SQL initialization for non-embedded databases
spring.sql.init.mode=always

#Enable Actuator Endpoints
management.endpoints.web.exposure.include=*
#increase the number of processes available for scheduling
spring.task.scheduling.pool.size=5

# Server Configuration
server.servlet.context-path=/api/v1
server.port=8081

# Swagger Configuration
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Security Configuration
#jwt.secretKey=${JWT_SECRET_KEY}
jwt.secretKey=SZ7VZXSzB3ewqQR5vEAKE7FjKKLeeFhUnrsTYCPQrfq

# Frontend URL
frontend.url=${FRONTEND_URL:http://localhost:3000}

# Scheduling Configuration
blog.schedulers.userDeletion.cron=0 0 0 * * *
blog.schedulers.viewSync.cron=0 */5 * * * *
blog.schedulers.publishPost.cron=0 * * * * *

# Data Compression
server.compression.enabled=true
# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:blog_redis}
#docker run \
#--name blog-management-postgres \
#-e POSTGRES_PASSWORD=blog_admin \
#-e POSTGRES_USER=root \
#-e POSTGRES_DB=blog_management_system \
#-p 5433:5432 \
#postgres:16.13-alpine3.23@sha256:6ba5f528786dcc296ab4b6d70c1699d224659583e6df320ee1c39e33b4111820
#docker run -d \
#  --name blog-management-redis \
#  -p 6379:6379 \
#  redis:7-alpine \
#  redis-server --requirepass "blog_redis"